import "~/styles/globals.css";
import { api, HydrateClient } from "~/trpc/server";

import { type Metadata } from "next";

import Navbar from "./_components/navbar";

export const metadata: Metadata = {
  title: "Senior - Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ProjectsLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  void api.project.getAll.prefetch();

  return (
    <HydrateClient>
      <Navbar />
      {children}
    </HydrateClient>
  );
}
