import "~/styles/globals.css";
import { api, HydrateClient } from "~/trpc/server";
import { getServerAuthSession } from "~/server/auth";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "../_components/navbar";

export const metadata: Metadata = {
  title: "Senior - Project Management",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ProjectsLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  void api.project.getAll.prefetch();

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <HydrateClient>
            <Navbar />
            {children}
          </HydrateClient>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
