import "~/styles/globals.css";
import { HydrateClient } from "~/trpc/server";

import { type Metadata } from "next";

import Navbar from "./../dashboard/_components/navbar";

export const metadata: Metadata = {
  title: "Senior - Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ProjectsLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <HydrateClient>
      <div className="flex min-h-screen flex-col bg-gray-200">
        <Navbar />
        {children}
      </div>
    </HydrateClient>
  );
}
