import "~/styles/globals.css";
import { api, HydrateClient } from "~/trpc/server";

import { type Metadata } from "next";

import Navbar from "./_components/navbar";
import { getServerAuthSession } from "~/server/auth";

export const metadata: Metadata = {
  title: "Senior - Dashboard",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function ProjectsLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  if (session) {
    void api.template.getAll.prefetch();
  }

  return <HydrateClient>{children}</HydrateClient>;
}
